S92.38 Add message back
ExpandOnline/redis-http-push-queue pull request #15
Opened 2017-01-04 13:47 UTC by pvaass

2017-01-05 11:59 UTC, mtricht requested changes

2017-01-05 11:59 UTC, swordbeta commented on src/request.js
> +  const full = assoc('status_code', res.statusCode, withMessage);
```
R.merge({
  message: res.statusCode >= 300 ? '[ERROR] Bad response' : '[INFO] Response received',
  statusCode: res.statusCode
}, body);
```

2017-01-06 08:50 UTC, pvaass commented on src/request.js
> +  const full = assoc('status_code', res.statusCode, withMessage);
@swordbeta fixed

2017-01-06 08:51 UTC, mtricht approved these changes

2017-01-06 08:51 UTC, merged