S112.28 Add docker dirs
ExpandOnline/redis-http-push-queue pull request #19
Opened 2017-10-30 08:23 UTC by pvaass

2017-10-30 08:46 UTC, mtricht requested changes

2017-10-30 08:46 UTC, swordbeta commented on docker/redis-http-push-queue/Dockerfile
> +FROM node:5.11
Ik denk dat je deze versie omhoog moet bumpen; https://hub.docker.com/_/node/ zie hier geen 5 meer staan

2017-10-30 08:46 UTC, swordbeta commented on docker/redis-http-push-queue/commands/run
> +  --link redis:redis \
moet je dan apart redis starten met de naam redis?

2017-10-31 09:46 UTC, pvaass commented on docker/redis-http-push-queue/Dockerfile
> +FROM node:5.11
Thanks voor het checken!

2017-10-31 09:47 UTC, pvaass commented on docker/redis-http-push-queue/commands/run
> +  --link redis:redis \
Had het van david ctrl+c, heb de redis map er nu ook bij gedaan

2017-10-31 09:47 UTC, pvaass commented
@swordbeta Thanks!

2017-10-31 14:02 UTC, mtricht approved these changes

2017-11-01 09:33 UTC, merged